services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./create_service_account.sh:/usr/share/create_service_account.sh
      - ./.env:/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elastic:${ELASTIC_PASSWORD}@localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_service_user
      - ELASTICSEARCH_PASSWORD=kibana_service_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  python:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - .:/app
    command: ["python", "main.py"]
    network_mode: "host"

volumes:
  es_data: